import Head from "next/head";
import Card from "../components/Card";
import dbConnect from "../lib/dbConnect";
import Complaint from "../models/Complaint";

export default function Home({ complaints }) {
  const renderComplaints = () => {
    return complaints.map((complaint) => {
      return <Card key={complaint._id} complaint={complaint} />;
    });
  };

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen">
        <div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4">
          {renderComplaints()}
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  await dbConnect();

  const result = await Complaint.find({});
  const complaints = result.map((doc) => {
    const complaint = doc.toObject();
    complaint._id = complaint._id.toString();
    return complaint;
  });
  return { props: { complaints } };
}
